name: farmWise
description: "Emphasizing wisdom and smart solutions for farm management."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_switch: ^0.3.2
  carousel_slider: ^5.0.0

# Flutter configuration
flutter:
  # Ensures that the Material Icons font is included with your application
  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/images/onboarding/
    - assets/images/splash/

  # To add custom fonts to your application
  fonts:
    - family: Railway
      fonts:
        - asset: assets/fonts/railway/RailwayFont.otf
